apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer
  namespace: glugg-deployment
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      app: glugg-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
