name: Build

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Restore and save Nix store
      uses: nix-community/cache-nix-action@v7
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        gc-max-store-size-linux: 1073741824
        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-primary-key: never

    - name: Build front-end
      run: |
        nix build .#glugg-frontend --out-link glugg-frontend

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'glugg-frontend'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5

  build-backend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    concurrency:
      group: "docker"
      cancel-in-progress: false

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: glugg-org/glugg-backend

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Restore and save Nix store
      uses: nix-community/cache-nix-action@v7
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        gc-max-store-size-linux: 1073741824
        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-primary-key: never

    - name: Build back-end
      run: |
        nix build .#glugg-backend --out-link glugg-backend

    - name: Build container
      run: |
        nix build .#glugg-backend-container --out-link glugg-backend-container

    - name: Publish container
      run: |
        nix develop .#ci --command skopeo copy \
          --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
          docker-archive:./glugg-backend-container \
          docker://ghcr.io/glugg-org/glugg-backend:${{ github.sha }}

